
title: EvoAgent Diary
author: ValerioB88
email: valerio.biscione@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to share ideas about EvoAgent and the simulations to run with it.
theme: minima
base_url: /EvoAgent
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ValerioB88 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
